name: WauzCore
main: eu.wauz.wauzcore.WauzCore
website: http://wauz.eu/
version: Pallasite.5.Pre
api-version: 1.13
author: Nikolas Keller
depend: [MythicMobs, NoteBlockAPI]
commands:
  hub:
    description: Teleport to Hub
    usage: /hub
    permission: wauz.normal
  spawn:
    description: Teleport to Spawn
    usage: /spawn
    permission: wauz.normal
  home:
    description: Teleport to Home
    usage: /home
    permission: wauz.normal
  sethome:
    description: Set Home Location
    usage: /sethome
    permission: wauz.normal
  menu:
    description: Open a Menu
    usage: /menu [name]
    permission: wauz.normal
  group:
    description: Open the Group Menu
    usage: /group
    permission: wauz.normal
  grp:
    description: Send Message in Group Chat
    usage: /grp [text]
    permission: wauz.normal
  desc:
    description: Set the Group Description
    usage: /desc [text]
    permission: wauz.normal
  guild:
    description: Create a Guild
    usage: /guild [guildName]
  apply:
    description: Apply for a Guild
    usage: /apply [guildName]
  gld:
    description: Send Message in Guild Chat
    usage: /gld [text]
    permission: wauz.normal
  motd:
    description: Set the Guild Message of the Day
    usage: /modt [text]
    permission: wauz.normal
  tip:
    description: Prints a Tip in Chat
    usage: /tip
    permission: wauz.normal
  wzSystem:
    description: Print System Analytics
    usage: /wzSystem
    permission: wauz.system
  wzHeal:
    description: Heal and Feed Player
    usage: /wzHeal [player]
    permission: wauz.system
  wzExp:
    description: Gain Experience Points
    usage: /wzExp [player] [tier] [amount]
    permission: wauz.system
  wzEnter.dev:
    description: Enter Dev Instance
    usage: /wzEnter.dev [instance]
    permission: wauz.system
  wzEnter:
    description: Enter Instance
    usage: /wzEnter [instance]
    permission: wauz.system
  wzLeave:
    description: Leave Instance
    usage: /wzLeave
    permission: wauz.system
  wzKey:
    description: Change Dungeon Key Status
    usage: /wzKey [world (this)] [keyId] [status (0, 1, 2)]
    permission: wauz.system
  wzDebug:
    description: Toggle Debug Mode
    usage: /wzDebug
    permission: wauz.system
  wzDebug.magic:
    description: Toggle Magic Debug Mode
    usage: /wzDebug.magic
    permission: wauz.system
  wzDebug.crafting:
    description: Toggle Crafting Debug Mode
    usage: /wzDebug.crafting
    permission: wauz.system
  wzDebug.building:
    description: Toggle Building Debug Mode
    usage: /wzDebug.building
    permission: wauz.system
  wzDebug.ditems:
    description: Toggle Dungeon Items Debug Mode
    usage: /wzDebug.ditems
    permission: wauz.system
  wzRegPet:
    description: Registers Pet to Owner
    usage: /wzRegPet [playername] [entityid]
    permission: wauz.system
  wzGetPet:
    description: Get Pet from String
    usage: /wzGetPet [playername] [petname]
    permission: wauz.system
  wzTravel:
    description: Phantom-Travel to Location
    usage: /wzTravel [x, y, z]
    permission: wauz.system
  wzTravelEvent:
    description: Event-Travel to Location per UUID
    usage: /wzTravelEvent [uuid]
    permission: wauz.normal
  wzSkill:
    description: Execute Skill
    usage: /wzSkill [skillname]
    permission: wauz.system
  wzSkill.weapon:
    description: Get Weapon with Skillgem
    usage: /wzSkill.weapon [skillname]
    permission: wauz.system
permissions:
  wauz.system:
    description: Gives access to system commands.
    default: op
  wauz.normal:
    description: Permission assigned to new players.
    default: true
  wauz.debug:
    description: Shows the debug log in chat.
    default: false
  wauz.debug.magic:
    description: Infinite mana and 1 second cooldowns.
    default: false
  wauz.debug.crafting:
    description: Unlock all recipes, craftable without cost.
    default: false
  wauz.debug.building:
    description: Enables building in all areas.
    default: false
  wauz.debug.ditems:
    description: Grants access to all dungeon items.
    default: false